### ISSUE TITLE
Deadlocks. Errors retrieving autoincrement values.

### ISSUE THREAD

**Issue by OllieJones** [OllieJones/index-wp-users-for-speed#18]
@paddy https://wordpress.org/support/topic/process-fails-and-doesnt-recover/ reported errors and deadlocks in the insertion of the usermeta data we use for rapidly querying by role.

His site is quite big, several hundred kilousers.

**Comment by paddy** [comment]
Hi @OllieJones thanks for letting me know, but you have definitely tagged the wrong paddy! ;)

**Comment by OllieJones** [comment]
Sorry 'bout that. That's my user's handle on https://w.org/
