### ISSUE TITLE
Can't delete users with plugin enabled

### ISSUE THREAD

**Issue by jasongill** [OllieJones/index-wp-users-for-speed#2]
Hey guys, our site has a few hundred thousand users and this plugin has been a big help. However, we are no longer able to delete users - when we go to the Users section of wp-admin, and click "Delete" for a user, the next page where you're given the option to reassign posts made by the user doesn't load (specifically, it stops at the dropdown that would list choices of users to reassign to).

The error given is:

```
PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, string given in wp-content/plugins/index-wp-users-for-speed/admin/user-handler.php:219
Stack trace:
#0 wp-content/plugins/index-wp-users-for-speed/admin/user-handler.php(219): in_array()
#1 wp-content/plugins/index-wp-users-for-speed/admin/user-handler.php(192): IndexWpUsersForSpeed\UserHandler->filtered_query_args()
#2 wordpress/wp-includes/class-wp-hook.php(307): IndexWpUsersForSpeed\UserHandler->filter__wp_dropdown_users_args()
#3 wordpress/wp-includes/plugin.php(191): WP_Hook->apply_filters()
#4 wordpress/wp-includes/user.php(1637): apply_filters()
#5 wordpress/wp-admin/users.php(371): wp_dropdown_users()
#6 {main}
  thrown in wp-content/plugins/index-wp-users-for-speed/admin/user-handler.php on line 219
```

when using version 1.0.2 of this plugin and 6.0.2 of WordPress.

I'll start trying to track down the issue and submit a PR if I can figure it out, but figured that I would submit the issue in the meantime to see if there is something we are missing or have set wrong. Thanks for your great plugins, perfect for large sites like ours!

**Comment by OllieJones** [comment]
Fixed, I believe, in 1.0.3

**Comment by jasongill** [comment]
This is fixed, thanks @OllieJones!

I am going to explore a way to just get rid of that step (selecting "delete all" or picking a user to reassign to), since the dropdown has 300,000+ options and often causes the browser to crash... maybe I'll submit a PR if I get a solution.

**Comment by OllieJones** [comment]
You're welcome. Thanks again for letting me know about the bug.
